# dodrio_templating/Makefile.toml
# https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

#region: public callable tasks/flows

    [tasks.default]
    description = "show list of public callable tasks"
    clear = true
    command = "cargo"
    args = ["make","--list-all-steps"]

    [tasks.dev]
    description = "cargo build development"
    clear = true
    dependencies = [
        "build_dev",
        "post_build",
    ]

    [tasks.release]
    description = "cargo build release"
    clear = true
    dependencies = [
        "build_release",
        "post_build",
    ]

    [tasks.publish]
    description = "publish the webfolder to google vm"
    # Firt copies the content of /dodrio_templating/webfolder to //googlecloud/ folder and then to google vm with use of sshagent."
    workspace = false
    clear = true
    # backslash is the escape character for all other special characters.
    # and then another time I have to escape the backslash. So 4 backslash for one backslash.
    script = [
        "rsync -avz --delete-after /home/luciano/rustprojects/dodrio_templating/css/ /home/luciano/rustprojects/googlecloud/var/www/html/dodrio_templating/css/",
        "rsync -avz --delete-after /home/luciano/rustprojects/dodrio_templating/pkg/ /home/luciano/rustprojects/googlecloud/var/www/html/dodrio_templating/pkg/",
        "rsync -avz --delete-after /home/luciano/rustprojects/dodrio_templating/index.html /home/luciano/rustprojects/googlecloud/var/www/html/dodrio_templating/index.html",
        "rsync -e ssh -avz --delete-after /home/luciano/rustprojects/googlecloud/var/www/html/dodrio_templating/ luciano_bestia@34.87.17.103:/var/www/html/dodrio_templating/",
    ]
# endregion

[tasks.build_dev]
clear = true
private = true
command = "wasm-pack"
args = ["build", "--target", "web","--dev", "--no-typescript"]

[tasks.build_release]
clear = true
private = true
command = "wasm-pack"
args = ["build","--target", "web","--release", "--no-typescript"]

[tasks.post_build]
clear = true
private = true
windows_alias = "windows_post_build"
linux_alias = "linux_post_build"

[tasks.windows_post_build]
clear = true
private = true
script = [
    # chrome has a super security for cross-origin and it does not work well here
    #"start chrome http://127.0.0.1:8186#t2", 
    #"start \"firefox\" \"C:\\Program Files\\Mozilla Firefox\\firefox.exe\" 127.0.0.1:8186",
    "basic-http-server -a 127.0.0.1:8186",
]

[tasks.linux_post_build]
clear = true
private = true
script = [
    "alias chrome=\"/mnt/c/Program\\ Files\\ \\(x86\\)/Google/Chrome/Application/chrome.exe\"",
    #"chrome http://127.0.0.1:8186#t2", 
    "basic-http-server -a 127.0.0.1:8186",
]
